.gitignore, Makefile, README.md, conf.py, index.rst, make.bat, membership/admin.rst, setup/registration.rst
This adds a basic skeleton for the documentation.
It does not yet setup any infrastructure to publish the docs anywhere.
=> [MRG] Add first skeleton of sphinx docs

source/index.rst, source/membership/adding.rst, source/membership/removing.rst
=> adding first articles

source/index.rst, source/quickstart/product.rst, source/quickstart/setup.rst, source/quickstart/toggling.rst, source/quickstart/upgrade.rst
=> adds one new directory and four articles[MRG]

source/account/billing.rst, source/index.rst, source/quickstart/product.rst, source/quickstart/setup.rst, source/quickstart/toggling.rst, source/quickstart/upgrade.rst
Adds the account directory and one article. Ready for merge.
=> Add account

source/index.rst, source/quickstart/product.rst
=> adds new section heading structure for articles[MRG]

source/_static/css/custom.css
We said no visual tweaking till we have structure and content ... but the big orange logo was making my eyes hurt :D Thanks @fursinger for the CSS wizardry!
=> [MRG] Tweak the logo CSS to make it smaller

source/users/addmin.rst
more consistent language and punctuation
=> minor text edit

source/index.rst, source/users/modifying.rst
Removed users/modifying from the index (empty entry)
=> [MRG] Removed users/modifying

source/quickstart/setup.rst, source/quickstart/upgrade.rst
Replaced broken link https://help.skribble.com/creating-account/ with https://my.skribble.com/signup and updated instructions
=> [MRG] Replaced broken link

source/quickstart/signature.rst
Updated the following:
- Removed information that is not relevant to non-business customers
- Added link to the HP article explaining how visual signatures are created and used 
- Added note "available to enterprise and business customers only"
- Removed note that the article describes a feature that is only available to Enterprise and Business customers
=> [MRG] Visual signature content updates

source/index.rst, source/quickstart/onboard.rst
Added a new entry to the current index -> quickstart/onboard
=> [MRG] Various changes for Skribble Business

source/quickstart/onboard.rst
Added a note to the Quick Start Guide that video identification is only permitted for signing electronically according to EU law.
=> [MRG] Updated Quick Start Guide 

source/members/removing.rst
Added a note to Removing members from Skribble Business
=> [MRG] Added a note

source/conf.py, source/quickstart/members.rst
Removed Adding members by domain from the note
=> [MRG] Small tweaks

source/members/adding.rst
=> [fix] typo

source/account/signatureusage.rst
=> [MRG] Content updates

source/api/apicreate.rst
Updated the link to API documentation.
=> [MRG] API documentation

source/integrations/google.rst
=> [MRG] Typo

source/aes/AESproduct.rst
=> [MRG] Dead link

source/integrations/sign-google-drive.rst, source/integrations/sign-onedrive-sharepoint.rst
https://www.youtube.com/watch?v=BYMBYMwClHc&feature=youtu.be
=> [MRG] link update

source/integrations/microsoft.rst
https://appsource.microsoft.com/en/product/web-apps/skribbleag1597856521198.skribble-electronic-signature?tab=Overview
=> [MRG] Added direct link MS AppSource

source/account/deletionperiod.rst
Added a description that covers both existing and new customers
=> [MRG] Document deletion period old + new

source/account/signatureusage.rst
=> [MRG] Signature usage report

source/account/branding.rst
=> [MRG] Company branding note update

source/integrations/google.rst, source/integrations/microsoft.rst
with click here to get the plug-in
=> [MRG] Replaced download in wording

source/account/branding.rst, source/account/signatureusage.rst, source/account/visualsignature.rst, source/integrations/google.rst, source/integrations/microsoft.rst
This needs to be done for the product update email sent to customers on Friday.
=> [MRG] Adding a tag NEW for new articles

source/integrations/microsoft.rst
- You’ll be asked to allow installing the plug-in for all users on behalf of your organisation
- Select the checkbox **Consent on behalf of your organisation** and click **Accept** if you agree
=> [MRG] Consent and Cache update

source/account/deletionperiod.rst
updated the note for old ENT customers to make sure they know that they have to contact us if they want to introduce the new deletion period.
=> [MRG] Note update

source/account/branding.rst
Replaces support @skribble.com  with the form
=> [MRG] New form for CB

source/account/cancel.rst, source/quickstart/trial.rst
Added a note about what happens to documents after SB is deleted.
=> [MRG] Content update SB deleted

source/index.rst, source/members/adding.rst, source/members/removing.rst
=> [MRG] Index update

source/quickstart/admin.rst
Updated bullet points and instructions on how to access Business profile
=> [MRG] Update content

source/integrations/google.rst
Added note about the individual installation
=> [MRG] Update article for individual installation

source/integrations/microsoft.rst
Admins seem not to know that only 1 API key is needed.
=> [MRG] Add a note about number of keys needed

source/account/deletionperiod.rst
Updated the article for the new deletion period.
=> [MRG] NEW Deletion period update

source/account/deletionperiod.rst
Some update for the product update email
=> [MRG] Deletion period

source/account/deletionperiod.rst
Adding more anchor links
Changing the structure of the article
Adding some screenshots
=> [MRG] Deletion period update

source/aes/setup.rst, source/billing/payment-method.rst
Add note about cancelling AES for Business
Invoice as payment method
=> [MRG] Content updates 

source/billing/payment-method.rst
Removing the note about invoice :)
=> [MRG] Remove invoice

source/billing/payment-method.rst
Updated note regarding paying by invoice
=> [MRG] Payment method update

source/quickstart/upgrade.rst
We have changed the navigation labels mentioned in this article.
=> [MRG] Navigation update for SB

source/quickstart/onboard.rst
CH number only is wrong
Domains and company email address needs an update
=> [MRG] Get started guide update
